### ISSUE TITLE
Export Data button doesn't work in development but does in production

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/who-owns-what#194]
In development, "Export Data" oddly downloads an empty CSV that just says {"error":"403 - \"Authentication parameters missing\""}, but seems to work fine in Production...

**Comment by toolness** [comment]
Ok so I was wondering why the "export data" button was actually working on my computer and I think it is actually because we are not fully rid of the GeoClient code!!  I thought we were, but looking at the code in [`server/controllers/address.js`](https://github.com/JustFixNYC/who-owns-what/blob/master/server/controllers/address.js), it seems we are actually using GeoClient to geolocate the building's address if we are given the street address but not the BBL for it.

Since GeoClient requires authentication, it would make sense that it would return some kind of "authentication parameters missing" sort of error if your environment doesn't have the geoclient credentials in it... Do you have `GEOCLIENT_ID` and `GEOCLIENT_KEY` defined in your root (server) `.env` file?  If not, that explains it!

Obviously we should wean ourselves off this (hopefully) last bit of GeoClient code and replace it with GeoSearch, though!

**Comment by sraby** [comment]
Bingo! I had commented those vars out... now it works fine
